### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by bmontana-edu** [willbaschab/COOP_2018#1]
[Chapter03/U03_EX03_MolecularWeight.py](https://github.com/willbaschab/COOP_2018/commit/f3e9072fa6efd2481a90392aadf139501d3095fd#diff-cc586678eb14d20a213b9fa993581ba7)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Mark this issue resolved when you have fixed everything mentioned.

**Comment by willbaschab** [comment]
I have pushed my files, and fixed them according to said comments.
