### ISSUE TITLE
Algorithm/code mismatch

### ISSUE THREAD

**Issue by bmontana-edu** [willbaschab/COOP_2018#2]
[Chapter03/U03_EX14_AverageofNumSeries.py](https://github.com/willbaschab/COOP_2018/commit/f3e9072fa6efd2481a90392aadf139501d3095fd#diff-e110f8f4eb5b5712ad4798ce43f494d2)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Mark this issue resolved when you have fixed everything mentioned.

**Comment by willbaschab** [comment]
I have fixed my code and will commit it!
