### ISSUE TITLE
Detail needed: U03_EX10

### ISSUE THREAD

**Issue by bmontana-edu** [willbaschab/COOP_2018#3]
[Chapter03/U03_EX10_LadderLength.py](https://github.com/willbaschab/COOP_2018/commit/784e521d01fe034793b9ac6b526630f0fb3f6d45#diff-7f1e8a609c2adb6c81ce969a622ce6ca)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Close this issue when you have fixed everything mentioned.

**Comment by willbaschab** [comment]
This issue has been resolved after careful consideration. The problem has been fixed, and I will be closing this issue.
